### ISSUE TITLE
[BUG] 壓縮圖片版本上線 dev 後， 現在似乎圖片不會出現

### ISSUE THREAD

**Issue by vito588p** [astrocamp/14th-JoBand#132]
如圖示：
更新個人資料，上傳圖片後，也還是沒有出現

<img width="1036" alt="截圖 2023-09-07 下午11 45 37" src="https://github.com/astrocamp/14th-JoBand/assets/128116961/16d137d6-995e-4846-a3ca-adddc150e64c">

**Comment by andy840818** [comment]
me too

**Comment by zhanjian0217** [comment]
<img width="413" alt="image" src="https://github.com/astrocamp/14th-JoBand/assets/100756999/065ea481-62da-4f92-a422-85e1ca60d0e3">

你們終端機輸入 `which vips` 看看

不然就要 install libvips
https://www.libvips.org/install.html

**Comment by vito588p** [comment]
vips not found

**Comment by andy840818** [comment]
libvips-dev：
libvips-dev軟件包包含VIPS 圖像處理庫的開發文件和頭文件。這些文件對於編譯和鏈接需要使用VIPS 的應用程序或開發自己的圖像處理工具非常重要。
安裝libvips-dev允許您開發和構建使用VIPS 庫的自定義程序。如果您計劃使用VIPS API 編寫自己的圖像處理應用程序，那麼您需要安裝這個軟件包。

libvips-tools：
libvips-tools軟件包包含了一組命令行工具，允許您在終端中直接執行各種圖像處理操作。這些工具可以用來快速處理圖像，而無需編寫自定義應用程序。
安裝libvips-tools允許您立即在命令行中使用VIPS 的功能，例如轉換圖像格式、調整大小、裁剪、合併等等。
