### ISSUE TITLE
[規範] 圖片 image 擺放位置

### ISSUE THREAD

**Issue by vito588p** [astrocamp/14th-JoBand#52]
現在有放在 public 下
也有放在 asset/image 下

之後可能統一擺放在 public/image ?

可討論，團隊統一即可

**Comment by andy840818** [comment]
你說在 asset/image 要撈比較簡潔的話 , 我覺得較合適

**Comment by LeoChang0808** [comment]
投 public/images 一票ＸＤ

撈的時候其實差不多，前面的 public 不用打～
等於如果不放 images 資料夾路徑寫一樣～多一個 “/” 的樣子
如果要放 images 資料夾管理也只是多 “/images"

差別只是網頁上呈現的圖片路徑 asset/image 會是亂碼
public/images 不會而已～
（ 我常常會網路上點右鍵下載圖所以看見檔名亂碼有點白眼ＸＤ ） 
 
 一樣團隊統一即可 ^^ b
